# Development Profile Configuration

# Database Configuration (To be configured)
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/my-shop
#    driverClassName: org.postgresql.Driver
#    username: 
#    password: 
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true

#logging:
#  level:
#    root: INFO
#    com.my_shop: DEBUG
#    org.springframework.web: INFO
