# Production Profile Configuration

# Database Configuration (To be configured)
#spring:
#  datasource:
#    url: jdbc:postgresql://production-host:5432/my-shop
#    driverClassName: org.postgresql.Driver
#    username: 
#    password: 
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: false

#logging:
#  level:
#    root: WARN
#    com.my_shop: INFO
#    org.springframework.web: WARN
